#!/usr/bin/env bash
set -Eeuo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SERVER_BINARY="${ROOT_DIR}/target/release/nyro-server"
IMAGE_TAG="nyro:mine"
OUTPUT_ARCHIVE="${ROOT_DIR}/nyro-mine.tar"
ENV_FILE="${ROOT_DIR}/.env"
BUILD_CONTEXT=""
TEMP_ARCHIVE=""

die() {
    echo "error: $*" >&2
    exit 1
}

cleanup() {
    if [[ -n "${BUILD_CONTEXT}" ]]; then
        rm -rf -- "${BUILD_CONTEXT}"
    fi
    if [[ -n "${TEMP_ARCHIVE}" ]]; then
        rm -f -- "${TEMP_ARCHIVE}"
    fi
}

generate_admin_token() {
    if command -v openssl >/dev/null 2>&1; then
        openssl rand -hex 32
    elif command -v od >/dev/null 2>&1; then
        od -An -N32 -tx1 /dev/urandom | tr -d ' \n'
    else
        die "openssl or od is required to generate NYRO_ADMIN_TOKEN"
    fi
}

ensure_compose_env() {
    local admin_token proxy_auth_key

    if [[ -e "${ENV_FILE}" && ! -f "${ENV_FILE}" ]]; then
        die "${ENV_FILE} exists but is not a regular file"
    fi

    # The proxy port is published on 0.0.0.0 by compose.yaml, so the data plane
    # must always carry a Bearer key; generate one when missing.
    if [[ -f "${ENV_FILE}" ]]; then
        if ! grep -Eq '^NYRO_PROXY_AUTH_KEY=.+$' "${ENV_FILE}"; then
            if grep -Eq '^NYRO_PROXY_AUTH_KEY=$' "${ENV_FILE}"; then
                die "NYRO_PROXY_AUTH_KEY is empty in ${ENV_FILE}"
            fi
            proxy_auth_key="$(generate_admin_token)"
            printf '\nNYRO_PROXY_AUTH_KEY=%s\n' "${proxy_auth_key}" >> "${ENV_FILE}"
            chmod 0600 "${ENV_FILE}"
            echo "Added NYRO_PROXY_AUTH_KEY to ${ENV_FILE}"
        fi

        if grep -Eq '^NYRO_ADMIN_TOKEN=.+$' "${ENV_FILE}"; then
            chmod 0600 "${ENV_FILE}"
            return
        fi
        if grep -Eq '^NYRO_ADMIN_TOKEN=$' "${ENV_FILE}"; then
            die "NYRO_ADMIN_TOKEN is empty in ${ENV_FILE}"
        fi

        admin_token="$(generate_admin_token)"
        printf '\nNYRO_ADMIN_TOKEN=%s\n' "${admin_token}" >> "${ENV_FILE}"
        chmod 0600 "${ENV_FILE}"
        echo "Added NYRO_ADMIN_TOKEN to ${ENV_FILE}"
        return
    fi

    admin_token="$(generate_admin_token)"
    proxy_auth_key="$(generate_admin_token)"
    (
        umask 077
        printf '# Generated by make-docker.sh; keep this file private.\n' > "${ENV_FILE}"
        printf 'NYRO_ADMIN_TOKEN=%s\n' "${admin_token}" >> "${ENV_FILE}"
        printf 'NYRO_PROXY_AUTH_KEY=%s\n' "${proxy_auth_key}" >> "${ENV_FILE}"
    )
    echo "Created ${ENV_FILE} with random NYRO_ADMIN_TOKEN and NYRO_PROXY_AUTH_KEY"
}

command -v docker >/dev/null 2>&1 || die "docker is required"
command -v file >/dev/null 2>&1 || die "file is required"
docker info >/dev/null 2>&1 || die "the Docker daemon is not available"

[[ -x "${SERVER_BINARY}" ]] || die "${SERVER_BINARY} is missing; run 'make server' first"

BINARY_DESCRIPTION="$(file -b "${SERVER_BINARY}")"
case "${BINARY_DESCRIPTION}" in
    *ELF*x86-64*) TARGET_PLATFORM="linux/amd64" ;;
    *ELF*ARM*aarch64*) TARGET_PLATFORM="linux/arm64" ;;
    *)
        die "unsupported server binary (${BINARY_DESCRIPTION}); build it on Linux amd64 or arm64"
        ;;
esac

NYRO_VERSION="$("${SERVER_BINARY}" --version | awk 'NF >= 2 { print $2; exit }')"
[[ -n "${NYRO_VERSION}" ]] || NYRO_VERSION="dev"

BUILD_CONTEXT="$(mktemp -d)"
trap cleanup EXIT
install -m 0755 "${SERVER_BINARY}" "${BUILD_CONTEXT}/nyro-server"

echo "Building ${IMAGE_TAG} for ${TARGET_PLATFORM} from Nyro ${NYRO_VERSION}"
docker build \
    --platform "${TARGET_PLATFORM}" \
    --build-arg "NYRO_VERSION=${NYRO_VERSION}" \
    --file "${ROOT_DIR}/Dockerfile" \
    --tag "${IMAGE_TAG}" \
    "${BUILD_CONTEXT}"

TEMP_ARCHIVE="$(mktemp "${ROOT_DIR}/.nyro-mine.tar.XXXXXX")"
echo "Exporting ${IMAGE_TAG} to ${OUTPUT_ARCHIVE}"
docker image save --output "${TEMP_ARCHIVE}" "${IMAGE_TAG}"
chmod 0644 "${TEMP_ARCHIVE}"
mv -f -- "${TEMP_ARCHIVE}" "${OUTPUT_ARCHIVE}"
TEMP_ARCHIVE=""

ensure_compose_env

echo "Done:"
echo "  image:   ${IMAGE_TAG}"
echo "  archive: ${OUTPUT_ARCHIVE}"
echo "  next:    docker compose up -d"
