#!/usr/bin/env bash
set -Eeuo pipefail

# 以 native 方式本地启动 Nyro,配置语义与 compose.yaml 保持一致:
#   release 二进制 + .env(NYRO_ADMIN_TOKEN / NYRO_STORAGE_BACKEND / NYRO_LOG_LEVEL)
#   + 本地持久化数据目录 + 19530/19531 端口,前台运行,Ctrl+C 停止。
# 数据目录等价于 compose 的 nyro-data 卷,默认 ~/.nyro,可用 NYRO_DATA_DIR 覆盖。
#
# 局域网访问:以 NYRO_LAN=1 ./start-local.sh 启动,代理与管理界面监听 0.0.0.0;
# 自动生成/读取 .env 中的 NYRO_PROXY_AUTH_KEY,代理面强制 Bearer 鉴权。

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${ROOT_DIR}/.env"
SERVER_BINARY="${ROOT_DIR}/target/release/nyro-server"
DATA_DIR="${NYRO_DATA_DIR:-${HOME}/.nyro}"

die() {
    echo "error: $*" >&2
    exit 1
}

generate_admin_token() {
    if command -v openssl >/dev/null 2>&1; then
        openssl rand -hex 32
    elif command -v od >/dev/null 2>&1; then
        od -An -N32 -tx1 /dev/urandom | tr -d ' \n'
    else
        die "openssl or od is required to generate NYRO_ADMIN_TOKEN"
    fi
}

ensure_env() {
    if [[ -e "${ENV_FILE}" && ! -f "${ENV_FILE}" ]]; then
        die "${ENV_FILE} exists but is not a regular file"
    fi
    if [[ -f "${ENV_FILE}" ]]; then
        if grep -Eq '^NYRO_ADMIN_TOKEN=.+$' "${ENV_FILE}"; then
            chmod 0600 "${ENV_FILE}"
            return
        fi
        if grep -Eq '^NYRO_ADMIN_TOKEN=$' "${ENV_FILE}"; then
            die "NYRO_ADMIN_TOKEN is empty in ${ENV_FILE}"
        fi
        printf '\nNYRO_ADMIN_TOKEN=%s\n' "$(generate_admin_token)" >> "${ENV_FILE}"
        chmod 0600 "${ENV_FILE}"
        echo "Added NYRO_ADMIN_TOKEN to ${ENV_FILE}"
        return
    fi
    (
        umask 077
        printf '# Generated by start-local.sh; keep this file private.\n' > "${ENV_FILE}"
        printf 'NYRO_ADMIN_TOKEN=%s\n' "$(generate_admin_token)" >> "${ENV_FILE}"
    )
    echo "Created ${ENV_FILE} with a random NYRO_ADMIN_TOKEN"
}

ensure_proxy_key() {
    if grep -Eq '^NYRO_PROXY_AUTH_KEY=.+$' "${ENV_FILE}"; then
        return
    fi
    if grep -Eq '^NYRO_PROXY_AUTH_KEY=$' "${ENV_FILE}"; then
        die "NYRO_PROXY_AUTH_KEY is empty in ${ENV_FILE}"
    fi
    printf 'NYRO_PROXY_AUTH_KEY=%s\n' "$(generate_admin_token)" >> "${ENV_FILE}"
    echo "Added NYRO_PROXY_AUTH_KEY to ${ENV_FILE}"
}

# 与 docker compose 的取值优先级一致:已导入的环境变量 > .env > compose.yaml 默认值
env_get() {
    local key="$1" default="$2" val
    val="$(grep -E "^${key}=" "${ENV_FILE}" 2>/dev/null | tail -n1 | cut -d= -f2- || true)"
    echo "${val:-${default}}"
}

cd "${ROOT_DIR}"

if [[ ! -x "${SERVER_BINARY}" ]]; then
    echo "nyro-server binary missing; running 'make server' ..."
    make server
fi

ensure_env

# LAN 模式:监听 0.0.0.0 并强制代理鉴权(等价于服务端 --lan)
LAN_MODE=0
NYRO_LAN_VAL="${NYRO_LAN:-0}"
if [[ "${NYRO_LAN_VAL,,}" =~ ^(1|true|yes|on)$ ]]; then
    LAN_MODE=1
    ensure_proxy_key
    [[ -n "${NYRO_PROXY_AUTH_KEY:-}" ]] || NYRO_PROXY_AUTH_KEY="$(env_get NYRO_PROXY_AUTH_KEY "")"
    [[ -n "${NYRO_PROXY_AUTH_KEY}" ]] || die "missing NYRO_PROXY_AUTH_KEY in ${ENV_FILE}"
fi

[[ -n "${NYRO_ADMIN_TOKEN:-}" ]] || NYRO_ADMIN_TOKEN="$(env_get NYRO_ADMIN_TOKEN "")"
[[ -n "${NYRO_ADMIN_TOKEN}" ]] || die "missing NYRO_ADMIN_TOKEN in ${ENV_FILE}"
[[ -n "${NYRO_STORAGE_BACKEND:-}" ]] || NYRO_STORAGE_BACKEND="$(env_get NYRO_STORAGE_BACKEND sqlite)"
[[ -n "${NYRO_LOG_LEVEL:-}" ]] || NYRO_LOG_LEVEL="$(env_get NYRO_LOG_LEVEL info)"
export NYRO_ADMIN_TOKEN NYRO_STORAGE_BACKEND NYRO_LOG_LEVEL

mkdir -p "${DATA_DIR}"

if [[ "${LAN_MODE}" = 1 ]]; then
    echo "Starting Nyro (native, mode=all, LAN) ..."
    echo "  proxy:    http://0.0.0.0:19530  (LAN; Bearer auth required)"
    echo "  admin:    http://0.0.0.0:19531  (LAN; token required)"
    echo "  data:     ${DATA_DIR}"
    echo "  storage:  ${NYRO_STORAGE_BACKEND}"
    echo "  proxy key:   see ${ENV_FILE} (NYRO_PROXY_AUTH_KEY)"
    echo "  admin token: see ${ENV_FILE} (NYRO_ADMIN_TOKEN)"
    echo "  Ctrl+C to stop"
    echo
else
    echo "Starting Nyro (native, mode=all) ..."
    echo "  proxy:   http://127.0.0.1:19530"
    echo "  admin:   http://127.0.0.1:19531"
    echo "  data:    ${DATA_DIR}"
    echo "  storage: ${NYRO_STORAGE_BACKEND}"
    echo "  token:   see ${ENV_FILE} (NYRO_ADMIN_TOKEN)"
    echo "  Ctrl+C to stop"
    echo
fi

LAN_ARGS=()
if [[ "${LAN_MODE}" = 1 ]]; then
    LAN_ARGS=(--lan --proxy-auth-key "${NYRO_PROXY_AUTH_KEY}")
fi

exec "${SERVER_BINARY}" \
    --data-dir "${DATA_DIR}" \
    --storage-backend "${NYRO_STORAGE_BACKEND}" \
    --log-level "${NYRO_LOG_LEVEL}" \
    "${LAN_ARGS[@]}"
