-- Nyro AI Gateway — MySQL final post-migration reference schema
-- Generated by nyro-tools from nyro-core StorageBootstrap::init + migrate.
-- Derived artifact: do not edit SQL by hand. No application data is included.
-- Regenerate using a NEW EMPTY disposable database for each invocation:
-- NYRO_SCHEMA_DATABASE_URL='<scratch-url>' nyro-tools dump-schema --backend mysql --output deploy/schema/mysql.sql
-- See docs/database/schema.md for prerequisites and safety restrictions.

SET NAMES utf8mb4;

CREATE TABLE `api_keys` (
  `id` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `token` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `rpm` int DEFAULT NULL,
  `rpd` int DEFAULT NULL,
  `tpm` int DEFAULT NULL,
  `tpd` int DEFAULT NULL,
  `is_enabled` tinyint(1) DEFAULT '1',
  `is_privileged` tinyint(1) NOT NULL DEFAULT '0',
  `expires_at` datetime DEFAULT NULL,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `token` (`token`),
  KEY `idx_api_keys_token` (`token`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `providers` (
  `id` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `vendor` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `protocol` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `base_url` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `protocol_mode` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'fixed',
  `preset_key` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `channel` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `models_source` text COLLATE utf8mb4_unicode_ci,
  `static_models` text COLLATE utf8mb4_unicode_ci,
  `api_key` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `auth_mode` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'apikey',
  `access_token` text COLLATE utf8mb4_unicode_ci,
  `refresh_token` text COLLATE utf8mb4_unicode_ci,
  `expires_at` datetime DEFAULT NULL,
  `use_proxy` tinyint(1) NOT NULL DEFAULT '0',
  `fast_mode` tinyint(1) NOT NULL DEFAULT '0',
  `last_test_success` tinyint(1) DEFAULT NULL,
  `last_test_at` datetime DEFAULT NULL,
  `is_enabled` tinyint(1) DEFAULT '1',
  `priority` int DEFAULT '0',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `models` (
  `id` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `balance` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT 'weighted',
  `target_provider` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `target_model` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `enable_auth` tinyint(1) DEFAULT '0',
  `enable_payload` tinyint(1) DEFAULT NULL,
  `force_max_reasoning` tinyint(1) NOT NULL DEFAULT '0',
  `vision_shim` text COLLATE utf8mb4_unicode_ci,
  `is_enabled` tinyint(1) DEFAULT '1',
  `priority` int DEFAULT '0',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `target_provider` (`target_provider`),
  CONSTRAINT `models_ibfk_1` FOREIGN KEY (`target_provider`) REFERENCES `providers` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `api_key_models` (
  `api_key_id` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `model_id` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`api_key_id`,`model_id`),
  KEY `idx_api_key_routes_route_id` (`model_id`),
  CONSTRAINT `api_key_models_ibfk_1` FOREIGN KEY (`api_key_id`) REFERENCES `api_keys` (`id`) ON DELETE CASCADE,
  CONSTRAINT `api_key_models_ibfk_2` FOREIGN KEY (`model_id`) REFERENCES `models` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `model_backends` (
  `id` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `model_id` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `provider_id` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `model` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `weight` int DEFAULT '100',
  `priority` int DEFAULT '1',
  `is_fallback` tinyint(1) NOT NULL DEFAULT '0',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `provider_id` (`provider_id`),
  KEY `idx_route_targets_route_id` (`model_id`),
  CONSTRAINT `model_backends_ibfk_1` FOREIGN KEY (`model_id`) REFERENCES `models` (`id`) ON DELETE CASCADE,
  CONSTRAINT `model_backends_ibfk_2` FOREIGN KEY (`provider_id`) REFERENCES `providers` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `provider_model_ratings` (
  `provider_id` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `upstream_model` varbinary(1024) NOT NULL,
  `score` int NOT NULL,
  `updated_at` text COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`provider_id`,`upstream_model`),
  CONSTRAINT `provider_model_ratings_ibfk_1` FOREIGN KEY (`provider_id`) REFERENCES `providers` (`id`) ON DELETE CASCADE,
  CONSTRAINT `provider_model_ratings_chk_1` CHECK ((length(`upstream_model`) between 1 and 1024)),
  CONSTRAINT `provider_model_ratings_chk_2` CHECK ((`score` between 0 and 100))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `provider_oauth_credentials` (
  `provider_id` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `driver_key` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `scheme` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `access_token` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `refresh_token` text COLLATE utf8mb4_unicode_ci,
  `expires_at` datetime DEFAULT NULL,
  `resource_url` text COLLATE utf8mb4_unicode_ci,
  `subject_id` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `scopes` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `meta` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `status` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'connected',
  `status_version` int NOT NULL DEFAULT '0',
  `last_error` text COLLATE utf8mb4_unicode_ci,
  `last_refresh_at` datetime DEFAULT NULL,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`provider_id`),
  KEY `idx_oauth_creds_status` (`status`),
  KEY `idx_oauth_creds_expires` (`expires_at`),
  CONSTRAINT `provider_oauth_credentials_ibfk_1` FOREIGN KEY (`provider_id`) REFERENCES `providers` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `provider_protocol_endpoints` (
  `id` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `provider_id` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `protocol` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `base_url` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `api_key` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `auth_scheme` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'auto',
  `is_enabled` tinyint(1) NOT NULL DEFAULT '1',
  `priority` int NOT NULL DEFAULT '0',
  `test_status` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'untested',
  `test_error` text COLLATE utf8mb4_unicode_ci,
  `tested_at` datetime DEFAULT NULL,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_provider_protocol_endpoints_provider_protocol` (`provider_id`,`protocol`),
  KEY `idx_provider_protocol_endpoints_provider` (`provider_id`,`is_enabled`,`priority`),
  CONSTRAINT `provider_protocol_endpoints_ibfk_1` FOREIGN KEY (`provider_id`) REFERENCES `providers` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `request_logs` (
  `id` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` bigint NOT NULL DEFAULT '0',
  `api_key_id` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `api_key_name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `client_protocol` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `upstream_protocol` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `provider_id` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `provider_name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `model_id` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `model_name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `upstream_url` text COLLATE utf8mb4_unicode_ci,
  `client_model` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `upstream_model` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `reasoning_effort` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `route_decision` longtext COLLATE utf8mb4_unicode_ci,
  `method` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `path` text COLLATE utf8mb4_unicode_ci,
  `client_request_headers` text COLLATE utf8mb4_unicode_ci,
  `client_request_body` longtext COLLATE utf8mb4_unicode_ci,
  `client_response_headers` text COLLATE utf8mb4_unicode_ci,
  `client_response_body` longtext COLLATE utf8mb4_unicode_ci,
  `upstream_request_headers` text COLLATE utf8mb4_unicode_ci,
  `upstream_request_body` longtext COLLATE utf8mb4_unicode_ci,
  `upstream_response_headers` text COLLATE utf8mb4_unicode_ci,
  `upstream_response_body` longtext COLLATE utf8mb4_unicode_ci,
  `upstream_status_code` int DEFAULT NULL,
  `client_status_code` int DEFAULT NULL,
  `latency_total_ms` bigint DEFAULT NULL,
  `latency_upstream_ms` bigint DEFAULT NULL,
  `input_tokens` int DEFAULT '0',
  `output_tokens` int DEFAULT '0',
  `cache_read_tokens` int DEFAULT '0',
  `is_stream` tinyint(1) DEFAULT '0',
  `stream_chunks_count` int DEFAULT '0',
  `stream_first_chunk_ms` bigint DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_logs_created_at` (`created_at`),
  KEY `idx_logs_provider_id` (`provider_id`),
  KEY `idx_logs_client_status` (`client_status_code`),
  KEY `idx_logs_upstream_model` (`upstream_model`),
  KEY `idx_logs_api_key` (`api_key_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `settings` (
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `value` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
