-- Nyro AI Gateway — PostgreSQL final post-migration reference schema
-- Generated by nyro-tools from nyro-core StorageBootstrap::init + migrate.
-- Derived artifact: do not edit SQL by hand. No application data is included.
-- Regenerate using a NEW EMPTY disposable database for each invocation:
-- NYRO_SCHEMA_DATABASE_URL='<scratch-url>' nyro-tools dump-schema --backend postgres --output deploy/schema/postgres.sql
-- See docs/database/schema.md for prerequisites and safety restrictions.

--
-- PostgreSQL database dump
--

\restrict NyroSchemaDump


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: api_key_models; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.api_key_models (
    api_key_id text NOT NULL,
    model_id text NOT NULL
);


--
-- Name: api_keys; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.api_keys (
    id text NOT NULL,
    token text NOT NULL,
    name text NOT NULL,
    rpm integer,
    rpd integer,
    tpm integer,
    tpd integer,
    is_enabled boolean DEFAULT true,
    is_privileged boolean DEFAULT false NOT NULL,
    expires_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: model_backends; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.model_backends (
    id text NOT NULL,
    model_id text NOT NULL,
    provider_id text NOT NULL,
    model text NOT NULL,
    weight integer DEFAULT 100,
    priority integer DEFAULT 1,
    is_fallback boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: models; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.models (
    id text NOT NULL,
    name text NOT NULL,
    balance text DEFAULT 'weighted'::text,
    target_provider text NOT NULL,
    target_model text NOT NULL,
    enable_auth boolean DEFAULT false,
    enable_payload boolean,
    force_max_reasoning boolean DEFAULT false NOT NULL,
    vision_shim text,
    is_enabled boolean DEFAULT true,
    priority integer DEFAULT 0,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: provider_model_ratings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.provider_model_ratings (
    provider_id text NOT NULL COLLATE pg_catalog."C",
    upstream_model text NOT NULL COLLATE pg_catalog."C",
    score integer NOT NULL,
    updated_at text NOT NULL,
    CONSTRAINT provider_model_ratings_score_check CHECK (((score >= 0) AND (score <= 100))),
    CONSTRAINT provider_model_ratings_upstream_model_check CHECK (((octet_length(upstream_model) >= 1) AND (octet_length(upstream_model) <= 1024)))
);


--
-- Name: provider_oauth_credentials; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.provider_oauth_credentials (
    provider_id text NOT NULL,
    driver_key text DEFAULT ''::text NOT NULL,
    scheme text DEFAULT ''::text NOT NULL,
    access_token text DEFAULT ''::text NOT NULL,
    refresh_token text,
    expires_at timestamp with time zone,
    resource_url text,
    subject_id text,
    scopes text DEFAULT '[]'::text NOT NULL,
    meta text DEFAULT '{}'::text NOT NULL,
    status text DEFAULT 'connected'::text NOT NULL,
    status_version integer DEFAULT 0 NOT NULL,
    last_error text,
    last_refresh_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: provider_protocol_endpoints; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.provider_protocol_endpoints (
    id text NOT NULL,
    provider_id text NOT NULL,
    protocol text NOT NULL,
    base_url text NOT NULL,
    api_key text NOT NULL,
    auth_scheme text DEFAULT 'auto'::text NOT NULL,
    is_enabled boolean DEFAULT true NOT NULL,
    priority integer DEFAULT 0 NOT NULL,
    test_status text DEFAULT 'untested'::text NOT NULL,
    test_error text,
    tested_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: providers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.providers (
    id text NOT NULL,
    name text NOT NULL,
    vendor text,
    protocol text NOT NULL,
    base_url text NOT NULL,
    protocol_mode text DEFAULT 'fixed'::text NOT NULL,
    preset_key text,
    channel text,
    models_source text,
    static_models text,
    api_key text NOT NULL,
    auth_mode text DEFAULT 'apikey'::text NOT NULL,
    access_token text,
    refresh_token text,
    expires_at timestamp with time zone,
    use_proxy boolean DEFAULT false NOT NULL,
    fast_mode boolean DEFAULT false NOT NULL,
    last_test_success boolean,
    last_test_at timestamp with time zone,
    is_enabled boolean DEFAULT true,
    priority integer DEFAULT 0,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT providers_auth_mode_check CHECK ((auth_mode = ANY (ARRAY['apikey'::text, 'oauth'::text])))
);


--
-- Name: request_logs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.request_logs (
    id text NOT NULL,
    created_at bigint DEFAULT 0 NOT NULL,
    api_key_id text,
    api_key_name text,
    client_protocol text,
    upstream_protocol text,
    provider_id text,
    provider_name text,
    model_id text,
    model_name text,
    upstream_url text,
    client_model text,
    upstream_model text,
    reasoning_effort text,
    route_decision text,
    method text,
    path text,
    client_request_headers text,
    client_request_body text,
    client_response_headers text,
    client_response_body text,
    upstream_request_headers text,
    upstream_request_body text,
    upstream_response_headers text,
    upstream_response_body text,
    upstream_status_code integer,
    client_status_code integer,
    latency_total_ms bigint,
    latency_upstream_ms bigint,
    input_tokens integer DEFAULT 0,
    output_tokens integer DEFAULT 0,
    cache_read_tokens integer DEFAULT 0,
    is_stream boolean DEFAULT false,
    stream_chunks_count integer DEFAULT 0,
    stream_first_chunk_ms bigint
);


--
-- Name: settings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.settings (
    name text NOT NULL,
    value text NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: api_key_models api_key_routes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.api_key_models
    ADD CONSTRAINT api_key_routes_pkey PRIMARY KEY (api_key_id, model_id);


--
-- Name: api_keys api_keys_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.api_keys
    ADD CONSTRAINT api_keys_pkey PRIMARY KEY (id);


--
-- Name: api_keys api_keys_token_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.api_keys
    ADD CONSTRAINT api_keys_token_key UNIQUE (token);


--
-- Name: provider_model_ratings provider_model_ratings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.provider_model_ratings
    ADD CONSTRAINT provider_model_ratings_pkey PRIMARY KEY (provider_id, upstream_model);


--
-- Name: provider_oauth_credentials provider_oauth_credentials_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.provider_oauth_credentials
    ADD CONSTRAINT provider_oauth_credentials_pkey PRIMARY KEY (provider_id);


--
-- Name: provider_protocol_endpoints provider_protocol_endpoints_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.provider_protocol_endpoints
    ADD CONSTRAINT provider_protocol_endpoints_pkey PRIMARY KEY (id);


--
-- Name: provider_protocol_endpoints provider_protocol_endpoints_provider_id_protocol_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.provider_protocol_endpoints
    ADD CONSTRAINT provider_protocol_endpoints_provider_id_protocol_key UNIQUE (provider_id, protocol);


--
-- Name: providers providers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.providers
    ADD CONSTRAINT providers_pkey PRIMARY KEY (id);


--
-- Name: request_logs request_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.request_logs
    ADD CONSTRAINT request_logs_pkey PRIMARY KEY (id);


--
-- Name: model_backends route_targets_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.model_backends
    ADD CONSTRAINT route_targets_pkey PRIMARY KEY (id);


--
-- Name: models routes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.models
    ADD CONSTRAINT routes_pkey PRIMARY KEY (id);


--
-- Name: settings settings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.settings
    ADD CONSTRAINT settings_pkey PRIMARY KEY (name);


--
-- Name: idx_api_key_routes_route_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_api_key_routes_route_id ON public.api_key_models USING btree (model_id);


--
-- Name: idx_api_keys_token; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_api_keys_token ON public.api_keys USING btree (token);


--
-- Name: idx_logs_api_key; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_logs_api_key ON public.request_logs USING btree (api_key_id);


--
-- Name: idx_logs_client_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_logs_client_status ON public.request_logs USING btree (client_status_code);


--
-- Name: idx_logs_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_logs_created_at ON public.request_logs USING btree (created_at);


--
-- Name: idx_logs_provider_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_logs_provider_id ON public.request_logs USING btree (provider_id);


--
-- Name: idx_logs_upstream_model; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_logs_upstream_model ON public.request_logs USING btree (upstream_model);


--
-- Name: idx_oauth_creds_expires; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_oauth_creds_expires ON public.provider_oauth_credentials USING btree (expires_at);


--
-- Name: idx_oauth_creds_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_oauth_creds_status ON public.provider_oauth_credentials USING btree (status);


--
-- Name: idx_provider_protocol_endpoints_provider; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_provider_protocol_endpoints_provider ON public.provider_protocol_endpoints USING btree (provider_id, is_enabled, priority);


--
-- Name: idx_route_targets_route_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_route_targets_route_id ON public.model_backends USING btree (model_id);


--
-- Name: api_key_models api_key_routes_api_key_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.api_key_models
    ADD CONSTRAINT api_key_routes_api_key_id_fkey FOREIGN KEY (api_key_id) REFERENCES public.api_keys(id) ON DELETE CASCADE;


--
-- Name: api_key_models api_key_routes_route_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.api_key_models
    ADD CONSTRAINT api_key_routes_route_id_fkey FOREIGN KEY (model_id) REFERENCES public.models(id) ON DELETE CASCADE;


--
-- Name: provider_model_ratings provider_model_ratings_provider_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.provider_model_ratings
    ADD CONSTRAINT provider_model_ratings_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES public.providers(id) ON DELETE CASCADE;


--
-- Name: provider_oauth_credentials provider_oauth_credentials_provider_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.provider_oauth_credentials
    ADD CONSTRAINT provider_oauth_credentials_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES public.providers(id) ON DELETE CASCADE;


--
-- Name: provider_protocol_endpoints provider_protocol_endpoints_provider_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.provider_protocol_endpoints
    ADD CONSTRAINT provider_protocol_endpoints_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES public.providers(id) ON DELETE CASCADE;


--
-- Name: model_backends route_targets_provider_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.model_backends
    ADD CONSTRAINT route_targets_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES public.providers(id);


--
-- Name: model_backends route_targets_route_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.model_backends
    ADD CONSTRAINT route_targets_route_id_fkey FOREIGN KEY (model_id) REFERENCES public.models(id) ON DELETE CASCADE;


--
-- Name: models routes_target_provider_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.models
    ADD CONSTRAINT routes_target_provider_fkey FOREIGN KEY (target_provider) REFERENCES public.providers(id);


--
-- PostgreSQL database dump complete
--

\unrestrict NyroSchemaDump
